apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 3000 
      {{- if eq (.Values.service.type | default "NodePort") "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end }}
      protocol: TCP
  selector:
    app: grafana